server:
  port: 8080

spring:
  application:
    name: T-Bank-app
  datasource:
    url: jdbc:postgresql://db:5433/currency_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    user: postgres
    password: postgres
    url: jdbc:postgresql://db:5433/currency_tracker