version: '3.0'

services:

  db:
    image: postgres:15
    container_name: currency-db
    networks:
      - app_network
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_tracker
    ports:
      - "5433:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d currency_tracker" ]  # Проверка конкретной БД
      interval: 2s
      timeout: 2s
      retries: 30

  app:
    build: .
    container_name: currency-app
    networks:
      - app_network
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/currency_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_ENABLED: "true"

volumes:
  pg_data:

networks:
  app_network: